//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neckhozhin_Cursach.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employers()
        {
            this.Master_ = new HashSet<Master_>();
            this.Shift_Composition = new HashSet<Shift_Composition>();
            this.User_App = new HashSet<User_App>();
        }
    
        public int id_E { get; set; }
        public string Surname_E { get; set; }
        public string Name_E { get; set; }
        public string Patronymic_e { get; set; }
        public Nullable<int> Position_E { get; set; }
    
        public virtual Positions Positions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Master_> Master_ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shift_Composition> Shift_Composition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_App> User_App { get; set; }
    }
}
