//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neckhozhin_Cursach.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_()
        {
            this.OrderbyShift = new HashSet<OrderbyShift>();
        }
    
        public int id_O { get; set; }
        public Nullable<int> Product { get; set; }
        public Nullable<int> Paint { get; set; }
        public Nullable<int> Master_ { get; set; }
        public Nullable<int> Amount_Product { get; set; }
        public string Total_Area_Value { get; set; }
        public Nullable<decimal> Tatal_Area { get; set; }
    
        public virtual Master_ Master_1 { get; set; }
        public virtual Paint Paint1 { get; set; }
        public virtual Product Product1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderbyShift> OrderbyShift { get; set; }
    }
}
