//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neckhozhin_Cursach.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shift_Composition
    {
        public int id { get; set; }
        public Nullable<int> id_WS { get; set; }
        public Nullable<int> id_E { get; set; }
    
        public virtual Employers Employers { get; set; }
        public virtual Work_Shift Work_Shift { get; set; }
    }
}
