//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neckhozhin_Cursach.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supply_Details
    {
        public int id_S { get; set; }
        public Nullable<int> id_D { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
