//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neckhozhin_Cursach.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_App
    {
        public int id_U { get; set; }
        public Nullable<int> id_E { get; set; }
        public string UserName { get; set; }
        public string UserPassword { get; set; }
    
        public virtual Employers Employers { get; set; }
    }
}
